# Generated by Django 5.2.11 on 2026-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['billing', 'technical', 'account', 'general'])), name='valid_category_constraint'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high', 'critical'])), name='valid_priority_constraint'),
        ),
    ]
